//! Kabootar OS syscall table — unified kernel interface.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Syscall {
    Info,
    Read,
    Write,
    Spawn,
    Paint,
    Present,
    Sleep,
    DevList,
    DevOpen,
    DevClose,
    DevIoctl,
    GpuInfo,
    NetIfaces,
    NetConnect,
    NetListen,
    NetAccept,
    NetPoll,
    NetUdpBind,
    UsbList,
    AudioList,
    PermGrant,
    PermRevoke,
    PermList,
    PermCheck,
    SetSubject,
    HotplugPoll,
    HotplugRegister,
    HostInfo,
    Rename,
    Copy,
    Mount,
    Unmount,
    Mounts,
    MemFree,
    MemRead,
    MemWrite,
}

impl Syscall {
    pub fn from_name(name: &str) -> Option<Self> {
        match name.to_ascii_lowercase().as_str() {
            "info" => Some(Syscall::Info),
            "read" => Some(Syscall::Read),
            "write" => Some(Syscall::Write),
            "spawn" => Some(Syscall::Spawn),
            "paint" => Some(Syscall::Paint),
            "present" => Some(Syscall::Present),
            "sleep" => Some(Syscall::Sleep),
            "dev_list" | "devlist" => Some(Syscall::DevList),
            "dev_open" | "devopen" => Some(Syscall::DevOpen),
            "dev_close" | "devclose" => Some(Syscall::DevClose),
            "dev_ioctl" | "devioctl" => Some(Syscall::DevIoctl),
            "gpu_info" | "gpuinfo" => Some(Syscall::GpuInfo),
            "net_ifaces" | "netifaces" => Some(Syscall::NetIfaces),
            "net_connect" | "netconnect" => Some(Syscall::NetConnect),
            "net_listen" | "netlisten" => Some(Syscall::NetListen),
            "net_accept" | "netaccept" => Some(Syscall::NetAccept),
            "net_poll" | "netpoll" => Some(Syscall::NetPoll),
            "net_udp_bind" | "netudbind" => Some(Syscall::NetUdpBind),
            "usb_list" | "usblist" => Some(Syscall::UsbList),
            "audio_list" | "audiolist" => Some(Syscall::AudioList),
            "perm_grant" | "permgrant" => Some(Syscall::PermGrant),
            "perm_revoke" | "permrevoke" => Some(Syscall::PermRevoke),
            "perm_list" | "permlist" => Some(Syscall::PermList),
            "perm_check" | "permcheck" => Some(Syscall::PermCheck),
            "set_subject" | "setsubject" => Some(Syscall::SetSubject),
            "hotplug_poll" | "hotplugpoll" => Some(Syscall::HotplugPoll),
            "hotplug_register" | "hotplugregister" => Some(Syscall::HotplugRegister),
            "host_info" | "hostinfo" => Some(Syscall::HostInfo),
            "rename" => Some(Syscall::Rename),
            "copy" => Some(Syscall::Copy),
            "mount" => Some(Syscall::Mount),
            "unmount" => Some(Syscall::Unmount),
            "mounts" => Some(Syscall::Mounts),
            "mem_free" | "memfree" => Some(Syscall::MemFree),
            "mem_read" | "memread" => Some(Syscall::MemRead),
            "mem_write" | "memwrite" => Some(Syscall::MemWrite),
            _ => None,
        }
    }

    pub fn name(self) -> &'static str {
        match self {
            Syscall::Info => "info",
            Syscall::Read => "read",
            Syscall::Write => "write",
            Syscall::Spawn => "spawn",
            Syscall::Paint => "paint",
            Syscall::Present => "present",
            Syscall::Sleep => "sleep",
            Syscall::DevList => "dev_list",
            Syscall::DevOpen => "dev_open",
            Syscall::DevClose => "dev_close",
            Syscall::DevIoctl => "dev_ioctl",
            Syscall::GpuInfo => "gpu_info",
            Syscall::NetIfaces => "net_ifaces",
            Syscall::NetConnect => "net_connect",
            Syscall::NetListen => "net_listen",
            Syscall::NetAccept => "net_accept",
            Syscall::NetPoll => "net_poll",
            Syscall::NetUdpBind => "net_udp_bind",
            Syscall::UsbList => "usb_list",
            Syscall::AudioList => "audio_list",
            Syscall::PermGrant => "perm_grant",
            Syscall::PermRevoke => "perm_revoke",
            Syscall::PermList => "perm_list",
            Syscall::PermCheck => "perm_check",
            Syscall::SetSubject => "set_subject",
            Syscall::HotplugPoll => "hotplug_poll",
            Syscall::HotplugRegister => "hotplug_register",
            Syscall::HostInfo => "host_info",
            Syscall::Rename => "rename",
            Syscall::Copy => "copy",
            Syscall::Mount => "mount",
            Syscall::Unmount => "unmount",
            Syscall::Mounts => "mounts",
            Syscall::MemFree => "mem_free",
            Syscall::MemRead => "mem_read",
            Syscall::MemWrite => "mem_write",
        }
    }
}

pub fn list_syscalls() -> Vec<&'static str> {
    vec![
        "info",
        "read",
        "write",
        "spawn",
        "paint",
        "present",
        "sleep",
        "dev_list",
        "dev_open",
        "dev_close",
        "dev_ioctl",
        "gpu_info",
        "net_ifaces",
        "net_connect",
        "net_listen",
        "net_accept",
        "net_poll",
        "net_udp_bind",
        "usb_list",
        "audio_list",
        "perm_grant",
        "perm_revoke",
        "perm_list",
        "perm_check",
        "set_subject",
        "hotplug_poll",
        "hotplug_register",
        "host_info",
        "rename",
        "copy",
        "mount",
        "unmount",
        "mounts",
        "mem_free",
        "mem_read",
        "mem_write",
    ]
}
