$ErrorActionPreference = "Stop"

$root = Resolve-Path (Join-Path $PSScriptRoot "..")

# Alternate Cargo target directories are reproducible build output.
$targetDirs = Get-ChildItem $root -Directory |
    Where-Object { $_.Name -like "target-*" }
foreach ($dir in $targetDirs) {
    Remove-Item $dir.FullName -Recurse -Force
}

# Root-level bytecode spill files are generated by compiler/test runs.
$bytecode = Get-ChildItem $root -File |
    Where-Object { $_.Extension -in @(".kbc", ".kbcb") }
foreach ($file in $bytecode) {
    Remove-Item $file.FullName -Force
}

# Remove regenerable cinematic dependencies and intermediate frames.
$production = Join-Path $root "productions\kabootar-cinematic"
if (Test-Path $production) {
    $generatedDirs = @(
        "node_modules",
        "frames-v2",
        "native-frames",
        "native-test-frame",
        "science-frames",
        "science-previews",
        "science-test-frame"
    )
    foreach ($name in $generatedDirs) {
        $path = Join-Path $production $name
        if (Test-Path $path) {
            Remove-Item $path -Recurse -Force
        }
    }

    Get-ChildItem $production -File |
        Where-Object {
            $_.Name -like "review-*.png" -or
            $_.Name -like "preview-*.png" -or
            $_.Name -like "narration*.wav" -or
            $_.Name -like "narration*.mp3" -or
            $_.Extension -eq ".webm"
        } |
        Remove-Item -Force
}

# Python bytecode caches are always safe to regenerate.
Get-ChildItem $root -Directory -Recurse -Filter "__pycache__" |
    Remove-Item -Recurse -Force

Write-Host "Removed $($targetDirs.Count) target directories and $($bytecode.Count) bytecode spill files."
